name: myFirstWorkflow

# Trigger workflow on push
on:
  push:
  # schedule:
  #   - cron: "*/5 * * * *"
  # workflow_dispatch:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest

    steps:
      - name: Running Single Command in job1
        run: |
          pwd
          ls -ltr
          hostname

      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: Step 3
        run: |
          echo `pwd` >> myFirstWorkflow.txt 
          echo `ls -ltr` >> artifacts/list.txt
          echo `hostname` >> artifacts/hostname.txt
          hostname
      - name : upload Single file
        uses: actions/upload-artifact@v5.0.0
        with:
          name: single-file
          path : ./myFirstWorkflow.txt
      - name : upload Multiple files
        uses: actions/upload-artifact@v5.0.0
        with:
          name: multiple-files
          path : artifacts/
      - name : upload from multiple paths
        uses: actions/upload-artifact@v5.0.0
        with:
          name: multiple-files
          path : |
            ./myFirstWorkflow.txt
            artifacts/
      - name : upload from multiple paths with exclusions
        uses: actions/upload-artifact@v5.0.0
        with:
          name: multiple-files
          path : |
            ./myFirstWorkflow.txt
            artifacts/
            !**/hostname.txt
