name: myFirstWorkflow
# to work on every workflow on this branch
on: push
jobs:
  job1:
    name : job1
    runs-on : ubuntu-latest
    steps:
      - name : Running Single Command in job1
        run : echo 'HI' this is my first github workflow
      - name : Checking OS Release for Github hosted runners
        run : cat /etc/os-release
      - name: calling sleep
        run : sleep 20
  job2:
    name : job2
    runs-on: ubuntu-latest
    steps:
      - name: checking Hostname for Runner
        run: hostname
      - name: running multiple commands
        run : |
          echo "Hi from Arnav Bhatia"
          echo "current time is `date`"
          sleep 20
      
  job3:
    name: job3
    # ! run when job1  is completed
    needs : job1
    runs-on: ubuntu-latest 
    steps:
      - name : Job with single dependency
        run : sleep 5
  job4:
    name: job4
    # ! run when all are completed
    needs: [job1,job2,job3]
    runs-on: ubuntu-latest
    steps:
      - name : job for multiple dependencies
        run : sleep 5
